# Generated by Django 5.0.2 on 2024-04-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_generator', '0003_userlimit_user_alter_userlimit_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlimit',
            name='user',
        ),
        migrations.AlterField(
            model_name='userlimit',
            name='telegram_id',
            field=models.BigIntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
